Repository hack-throne/imdb-scrapper, pull requests merged in 2018-10, with the labels that each got.

#11 Added support for Today born star
  index.js
  lib/data.js
  package-lock.json
  package.json
  test.js
Labels: Hacktoberfest, enhancement

#9 Added support for TV episode summary, air date and rating. Added tests.
  index.js
  lib/episode.js
  test.js
Labels: do not merge

#10 Added functionality to get upcoming movies
  lib/upcoming.js
Labels: Hacktoberfest, enhancement

#14 Added actor info and actor search
  index.js
  lib/search.js
Labels: Hacktoberfest, do not merge
